import * as materialColor from 'material-ui/styles/colors';
import { lighten, darken, percentage } from 'utils/misc';

export default {
  ...materialColor,
  defaultPrimaryColor: 'rgba(0, 0, 0, 0.4)',
  darkPrimaryColor: 'rgba(0, 0, 0, 0.6)',
  almostBlack: 'rgba(0, 0, 0, 0.9)',
  colorSuccess: '#66BB6A',
  colorDanger: '#ff4c4c',
  colorGreen: '#66BB6A',
  colorRed: '#ff4c4c',
  colorBlue: '#6BF',
  colorMuted: '#727272',
  colorYelor: '#FFAB40',
  colorGolden: '#e5c100',
  green: '#66BB6A',
  blue: '#6BF',
  golden: '#e5c100',
  yelor: '#FFAB40',
  red: '#ff4c4c',
  lightGray: 'rgb(179, 179, 179)',
  colorBlueMuted: 'rgba(102, 187, 255, 0.3)',
  colorYelorMuted: 'rgba(255, 171, 64, 0.3)',
  colorMutedLight: 'rgb(179, 179, 179)',
  primaryLinkColor: '#6BF',
  textColorPrimary: '#F5F5F5',
  primaryTextColor: '#F5F5F5',
  textColorSecondary: '#212020',
  secondaryTextColor: '#212020',
  primarySurfaceColor: 'rgb(46, 47, 64)',
  secondarySurfaceColor: 'rgb(39, 39, 58)',
  tableHeaderSurfaceColor: 'rgba(0, 0, 0, .3)',
  tableRowOddSurfaceColor: 'rgba(255, 255, 255, .019)',
  tableRowEvenSurfaceColor: 'rgba(0, 0, 0, .019)',
  sliderTicksColor: '#757575',
  sliderTicksColorActive: '#337AB7',
  dividerColor: 'rgb(52, 50, 50)',
  fontFamily: `
      -apple-system, BlinkMacSystemFont,
      "Segoe UI",
      Roboto, "Droid Sans",
      Ubuntu, Cantarell,
      "Fira Sans",
      Helvetica, Arial, sans-serif`,
  fontWeightLight: '300',
  fontWeightNormal: '400',
  fontWeightMedium: '500',
  fontSizeCommon: '16px',
  fontSizeMedium: '14px',
  fontSizeSmall: '12px',
  fontSizeTiny: '10px',
  navDrawerWidth: '256px',
  normalTransition: 'all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms',
  linearTransition: 'all 300ms linear',

  /* calendar */
  'out-of-range-color': lighten('#333', 40),
  'out-of-range-bg-color': lighten('#333', 0.9),
  'calendar-border': '#DDD',
  'cell-border': '#DDD',
  'border-color': '#CCC',
  'segment-width': percentage(1 / 7),
  'time-selection-color': 'white',
  'time-selection-bg-color': 'rgba(0,0,0, .50)',
  'date-selection-bg-color': 'rgba(0,0,0, .10)',
  'event-bg': '#3174ad',
  // 'event-bg': 'transparent',
  'event-border': darken('#3174ad', 10),
  'event-color': '#fff',
  'event-border-radius': '5px',
  'event-padding': '2px 5px',
  'event-zindex': '4',
  'btn-color': '#373a3c',
  'btn-bg': '#fff',
  'btn-border': '#ccc',
  'current-time-color': '#74ad31',
  'rbc-css-prefix': 'rbc-i',
  'today-highlight-bg': '#383c4c',
};
